version: '3.4'

services:
  nginx:
    image: nginx
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true

  gateway:
    image: dlgateway:latest
    restart: unless-stopped
    network_mode: "host"
    expose:
      - "8080"
